// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgnlk0XuprNMlw7aNknxa7DpHsHATbHPo',
    appId: '1:783339653491:web:842abb70fcb8fd1b89dd06',
    messagingSenderId: '783339653491',
    projectId: 'jobasheet-1cccb',
    authDomain: 'jobasheet-1cccb.firebaseapp.com',
    storageBucket: 'jobasheet-1cccb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuEOE2RaxfZ6_BZZLW3gjsDqvNVRSzcZQ',
    appId: '1:783339653491:android:d5d166217955d69989dd06',
    messagingSenderId: '783339653491',
    projectId: 'jobasheet-1cccb',
    storageBucket: 'jobasheet-1cccb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrsXIFYGre_Vg7jruqwQ6rU5Jyzpcznzs',
    appId: '1:783339653491:ios:536042134a90ee3789dd06',
    messagingSenderId: '783339653491',
    projectId: 'jobasheet-1cccb',
    storageBucket: 'jobasheet-1cccb.appspot.com',
    iosClientId: '783339653491-agbit0pp38j0fdevseq0961m1bp5jsdu.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobasheet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrsXIFYGre_Vg7jruqwQ6rU5Jyzpcznzs',
    appId: '1:783339653491:ios:671ff223058c111189dd06',
    messagingSenderId: '783339653491',
    projectId: 'jobasheet-1cccb',
    storageBucket: 'jobasheet-1cccb.appspot.com',
    iosClientId: '783339653491-13f9deq7ltqc0pvvv7lmg1h92v62sk35.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobasheet.RunnerTests',
  );
}
